server:
  port: 8181
spring:
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        binder:
          brokers: broker
          defaultBrokerPort: 9092
          autoCreateTopics: true
      bindings:
        consumer-in-0:
          group: cache
          destination: new-location-country
  redis:
    host: redis-service
    port: 6379
    database: 0
