server:
  port: 8181
spring:
  redis:
    host: redis-service
    port: 6379
    database: 0
    timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0    
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        binder:
          brokers: broker
          defaultBrokerPort: 9092
          autoCreateTopics: true
      bindings:
        consumer-in-0:
          group: cache
          destination: new-location-country
