server:
  port: 8181
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        binder:
          brokers: broker
          defaultBrokerPort: 9092
          autoCreateTopics: true
        bindings:
          consumer-in-0:
          destination: new-location-country
          group: location-cache
