server:
  port: 8180
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker
          defaultBrokerPort: 9092
          autoCreateTopics: true
      bindings:
        producer-in-0:
          group: location-app
          destination: new-location-country
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-service:5432/senatus_web
    username: postgres
    password: postgresqlpwd
    platform: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  
