server:
  port: 8180
  servlet:
    context-path: /v1/api
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: PostgreSQLDialect
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker
          defaultBrokerPort: 9092
          autoCreateTopics: true
      bindings:
        producer-out-0:
          group: location-app
          destination: new-location-country
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-service:5432/senatus_web
    username: postgres
    password: postgresqlpwd
    platform: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 2000
resilience4j:
  ratelimiter:
    metrics:
      enabled: true
    instances:
      rateLimiterApi:
        register-health-indicator: true
        limit-for-period: 30
        limit-refresh-period: 60s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50
