server:
  port: 8180
  servlet:
    context-path: /v1/api

management:
  endpoint:
    restart:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, build, health
    enabled-by-default: true
  info:
    java:
      enabled: true
  health:
    status:
      http-mapping:
        up: 200
        down: 400

spring:
  jpa:
    open-in-view: false
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 250
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: broker
          defaultBrokerPort: 9092
          autoCreateTopics: true
      bindings:
        producer-out-0:
          group: location-app
          destination: new-location-country
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-service:5432/senatus_web
    username: postgres
    password: postgresqlpwd
    platform: postgres
    hikari:
      connectionTimeout: 20000
      minimum-idle: 5
      maximumPoolSize: 10
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 20
        one-indexed-parameters: false
        max-page-size: 2000
resilience4j:
  ratelimiter:
    metrics:
      enabled: true
    instances:
      rateLimiterApi:
        register-health-indicator: true
        limit-for-period: 30
        limit-refresh-period: 60s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50
logging:
  level:
    sql: debug
      org:
        hibernate:
          orm:
            jdbc:
              bind: trace
