server:
  port: 8181
spring:
  data:
    mongodb:
      host: mongo-service.database
      port: 27017
      database: location-document-tst
  cloud:
    function:
      definition: consumer
    stream:
      kafka:
        binder:
          brokers: broker.message
          defaultBrokerPort: 9092
          autoCreateTopics: true
      bindings:
        consumer-in-0:
          group: location-document
          destination: new-location-country
